server:
  port: 92

spring:
  application:
    name: goop-coupon

  # nacos
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.56.10:8848

  #db
  datasource:
    username: root
    password: root
    url: jdbc:mysql://192.168.56.10:3306/db_sms
    driver-class-name: com.mysql.jdbc.Driver

  #Redis配置
  redis:
    host: 192.168.56.10

mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
      logic-delete-value: 1
      logic-not-delete-value: 0
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl   #SQL慢检查
    map-underscore-to-camel-case: true      #驼峰映射



